# Generated by Django 3.1.5 on 2021-01-31 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('programacion', 'Programacion'), ('musica', 'Musica'), ('cronicas', 'Cronicas'), ('articulos', 'Articulos'), ('literatura', 'Literatura'), ('opinion', 'Opinion'), ('otros', 'Otros')], default='otros', max_length=200)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/$d')),
                ('excerpt', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('feutured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
