# Generated by Django 3.1.5 on 2021-01-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='feutured',
            new_name='featured',
        ),
    ]
