# Generated by Django 3.1.5 on 2021-02-01 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210131_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='day',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='month',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
