# Generated by Django 3.1.5 on 2021-02-01 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210201_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
