# Generated by Django 3.1.5 on 2021-02-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210203_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='email',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=50, unique=True),
        ),
    ]
