# Generated by Django 3.1.5 on 2021-02-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210203_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
